"""empty message

Revision ID: 81390ab77d5d
Revises: c4f762a2e495
Create Date: 2019-05-27 14:56:10.787109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81390ab77d5d'
down_revision = 'c4f762a2e495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
